<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');

$footerTopStaticBlock = $baseHelper->getConfigValue('footer_section/footer_top/static_block');

$footerColumnOneStaticBlock = $baseHelper->getConfigValue('footer_section/footer_middle/column_one_static_block');
$footerColumnTwoStaticBlock = $baseHelper->getConfigValue('footer_section/footer_middle/column_two_static_block');
$footerColumnThreeStaticBlock = $baseHelper->getConfigValue('footer_section/footer_middle/column_three_static_block');
$footerColumnFourStaticBlock = $baseHelper->getConfigValue('footer_section/footer_middle/column_four_static_block');

$footerMiddleStaticBlock = $baseHelper->getConfigValue('footer_section/footer_middle/footer_middle_static_block');

$bottomLeftStaticBlock = $baseHelper->getConfigValue('footer_section/footer_bottom/left_static_block');
$bottomRightStaticBlock = $baseHelper->getConfigValue('footer_section/footer_bottom/right_static_block');

$baseUrl = $baseHelper->getBaseUrl();
$mediaUrl = $baseHelper->getMediaUrl();
?>
<div class="footer-wrapper type1">
    <div class="footer-top">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerTopStaticBlock)->toHtml(); ?>
    </div>
    <div class="footer-columns">
        <div class="page-main">
            <div class="content-main">
                <div class="col-row">
                    <div class="item first col-large-3 col-medium-3 col-small-3 col-extrasmall-12">
                        <div class="item-inner">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerColumnOneStaticBlock)->toHtml(); ?>
                        </div>
                    </div>
                    <div class="item col-large-3 col-medium-3 col-small-3 col-extrasmall-12">
                        <div class="item-inner">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerColumnTwoStaticBlock)->toHtml(); ?>
                        </div>
                    </div>
                    <div class="item col-large-3 col-medium-3 col-small-3 col-extrasmall-12">
                        <div class="item-inner">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerColumnThreeStaticBlock)->toHtml(); ?>
                        </div>
                    </div>
                    <div class="item last col-large-3 col-medium-3 col-small-3 col-extrasmall-12">
                        <div class="item-inner">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerColumnFourStaticBlock)->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php if ($footerMiddleStaticBlock != '') { ?>
                <div class="footer-text-content">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerMiddleStaticBlock)->toHtml(); ?>
                </div>
            <?php } ?>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="page-main">
            <div class="content-main">
                <div class="left">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($bottomLeftStaticBlock)->toHtml(); ?>
                </div>
                <div class="right">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($bottomRightStaticBlock)->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
</div>