<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$customCss = $baseHelper->getConfigValue('theme_section/custom_settings/custom_css');
$customJs = $baseHelper->getConfigValue('theme_section/custom_settings/custom_js');
?>
<?php if ($customCss != '') { ?>
    <style>
    <?php echo $customCss; ?>        
    </style>
<?php } ?>
<?php if ($customJs != '') { ?>
    <script>
        require(['jquery'], function () {
    <?php echo $customJs; ?>
        });
    </script>
<?php } ?>
<?php
$addthisEnable = $baseHelper->getConfigValue('theme_section/addthis/enable');
$pubId = $baseHelper->getConfigValue('theme_section/addthis/pubid');

if ($addthisEnable) {
    ?>
    <div class="addthis_sharing_toolbox"></div>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $pubId; ?>" async="async"></script>
<?php } ?>
<link rel="stylesheet" href='//fonts.googleapis.com/css?family=Jost%3A300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic' type='text/css' />