<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>
<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$baseUrl = $baseHelper->getBaseUrl();
$ishome = $baseHelper->getIsHome();
$showHome = $baseHelper->getConfigValue('header_section/megamenu/show_home_link');
?>
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php if ($showHome) { ?>
            <li class = "level0 level-top <?php if ($ishome) { ?> active <?php } ?>">
                <a class = "level-top" href = "<?php echo $baseUrl; ?>">
                    <?php echo __('Home');
                    ?>
                </a>
            </li>
        <?php } ?>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
