<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New <i>Products</i>');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist) : ?>
    <?php
    $baseHelper = $this->helper('ET\Base\Helper\Data');
    
    $showNewLabel = $baseHelper->getConfigValue('category_section/product_labels/show_new_label');
    $showSaleLabel = $baseHelper->getConfigValue('category_section/product_labels/show_sale_label');
    
    $enableSlider = 1;

    $productColumnClass = '';
    if ($enableSlider == 1) {
        $productColumnClass = 'slider-li';
    } else {
        $productColumnClass = 'five-blocks';
    }
    ?>
    <div class="block widget block-new-products widget-products-section <?php if ($enableSlider == 1) { ?> slider-enabled <?php } ?> <?= /* @noEscape */ $mode ?>">
        <div class="section-title">
            <span><?= htmlspecialchars_decode($title) ?></span>
        </div>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <div class="list-row">
                    <ol class="product-items <?= /* @noEscape */ $type ?> <?php if ($enableSlider == 1) { ?> new-products-grid-slider owl-carousel owl-theme <?php } ?>">
                        <?php foreach ($items as $_item) : ?>
                            <li class="product-li <?php echo $productColumnClass; ?>">
                                <div class="product-item-info addto-in">
                                    <div class="pro-img">
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                                        </a>
                                        <?php
                                        if ($showNewLabel == 1) {
                                            $fromDate = $_item->getNewsFromDate();
                                            $toDate = $_item->getNewsToDate();

                                            if (isset($fromDate) && isset($toDate)) {
                                                $fromDate = strtotime($fromDate);
                                                $toDate = strtotime($toDate);
                                                $now = strtotime(date("Y-m-d h:m:s"));

                                                if ($fromDate <= $now && $now <= $toDate) {
                                                    ?>
                                                    <span class="new-label"><?php echo __('New'); ?></span>
                                                    <?php
                                                }
                                            }
                                        }

                                        if ($showSaleLabel == 1) {
                                            $special_price = number_format($_item->getSpecialPrice(), 2);
                                            $regular_price = number_format($_item->getPrice(), 2);
                                            if (isset($special_price) && $special_price > 0) {
                                                if ($special_price < $regular_price) {
                                                    $fromSpecialDate = $_item->getSpecialFromDate();
                                                    $toSpecialDate = $_item->getSpecialToDate();

                                                    if (isset($fromSpecialDate) && isset($toSpecialDate)) {
                                                        $fromSpecialDate = strtotime($fromSpecialDate);
                                                        $toSpecialDate = strtotime($toSpecialDate);
                                                        $now = strtotime(date("Y-m-d h:m:s"));

                                                        if ($fromSpecialDate <= $now && $now <= $toSpecialDate) {
                                                            ?>
                                                            <span class="sale-label"><?php echo __('Sale'); ?></span>
                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        ?>
                                    </div>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                   <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?= $block->getProductPriceHtml($_item, $type); ?>

                                        <?php if ($templateType) : ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>                                        

                                        <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($showCart) : ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()) : ?>
                                                                <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)) : ?>
                                                                    <button class="action tocart primary"
                                                                            data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                            type="button"
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                <?php else : ?>
                                                                    <?php
                                                                    $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                                    $postData = $postDataHelper->getPostData(
                                                                            $block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => (int) $_item->getEntityId()]
                                                                            )
                                                                    ?>
                                                                    <button class="action tocart primary"
                                                                            data-post='<?= /* @noEscape */ $postData ?>'
                                                                            type="button"
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php else : ?>
                                                                <?php if ($_item->getIsSalable()) : ?>
                                                                    <div class="stock available">
                                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                    </div>
                                                                <?php else : ?>
                                                                    <div class="stock unavailable">
                                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($showWishlist || $showCompare) : ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                                <a href="#"
                                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                                   class="action towishlist"
                                                                   data-action="add-to-wishlist"
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                                <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class); ?>
                                                                <a href="#" class="action tocompare"
                                                                   data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>